  mysql_root_password: devopstest
  mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
  mysql_users:
    - name: notesapp
      host: "%"
      password: devopstest
      priv: "note.*:ALL"