---
- name: Configurar servidor de aplicacao java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapps"
    - dbpassword: "devopstest"
  tasks:
    - name: Configurar hosts lab ansible
      lineinfile:
      dest: /etc/hosts
      state: present
      line: "{{item}}"
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01
    - name: Adicionar user de app
      user:
       name: app
       comment: Usuario de aplicacao
       uid: 500
    - name: instalacao do maven
      yum:
       name: maven
       state: latest
    - name: instalacao do java
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: criacao do diretorio
      file:
       path: /opt/notes
       state: directory
       owner: app
       group: app
    - name: Clone do repositorio Notes - app
      git:
        repo: ''
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Configurar arquivo de propriedades para camada de banco de dados
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Gerar pacote da aplicacao
      command: mvm -f /opt/notes/pom.xml package
      become_user: app
    - name: Registrar versao atual do pacote
      shell:
        cmd: mvn -o -q -Dexec.executable=echo -Dexec.args='${project.version}'
        chdir: /opt/notes/
      register: app_version
    - name: Configurar servico do Systend
      template:
       src: etc/systemd/system/notes.service
       dest: /etc/systemd/system/notes.service
      notify: reload daemon
    - name: Iniciar servico notes
      services:
       name: notes
       state: restarted
  roles:
      - configuracao-default-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes


